In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("customer_data.csv")

In [3]:
dataset

,name,age,gender,education,income,country,purchase_frequency,spending
0,Teresa Williams MD,42,Female,High School,53936,Slovenia,0.9,13227.120
1,Christine Myers,49,Female,Master,82468,Aruba,0.6,12674.040
2,Dwayne Moreno,55,Male,Bachelor,56941,Cyprus,0.3,5354.115
3,Amy Norton,24,Female,Bachelor,60651,Palau,0.2,2606.510
4,Tonya Adams,64,Male,Master,81884,Zambia,0.9,18984.780
...,...,...,...,...,...,...,...,...
995,Jason Haas,42,Female,PhD,98170,Bosnia and Herzegovina,0.7,17435.950
996,Sharon Valdez,39,Male,High School,59174,Eritrea,0.9,11662.830
997,Andrew Taylor,50,Male,Master,59808,Serbia,0.4,7196.160
998,Jessica Johnson,50,Female,Master,58272,Cyprus,0.7,13939.520
999,Brian Williams,38,Female,Bachelor,32512,Turkey,0.5,8312.800

In [4]:
dataset.columns

Index(['name', 'age', 'gender', 'education', 'income', 'country',
       'purchase_frequency', 'spending'],
      dtype='object')

In [5]:
dataset = dataset.drop(columns=['name'])

In [6]:
dataset

,age,gender,education,income,country,purchase_frequency,spending
0,42,Female,High School,53936,Slovenia,0.9,13227.120
1,49,Female,Master,82468,Aruba,0.6,12674.040
2,55,Male,Bachelor,56941,Cyprus,0.3,5354.115
3,24,Female,Bachelor,60651,Palau,0.2,2606.510
4,64,Male,Master,81884,Zambia,0.9,18984.780
...,...,...,...,...,...,...,...
995,42,Female,PhD,98170,Bosnia and Herzegovina,0.7,17435.950
996,39,Male,High School,59174,Eritrea,0.9,11662.830
997,50,Male,Master,59808,Serbia,0.4,7196.160
998,50,Female,Master,58272,Cyprus,0.7,13939.520
999,38,Female,Bachelor,32512,Turkey,0.5,8312.800

In [9]:
dataset= pd.get_dummies(dataset, columns=['gender', 'education', 'country'],drop_first=True)

In [10]:
dataset

,age,income,purchase_frequency,spending,gender_Male,education_High School,education_Master,education_PhD,country_Albania,country_Algeria,...,country_Uruguay,country_Uzbekistan,country_Vanuatu,country_Venezuela,country_Vietnam,country_Wallis and Futuna,country_Western Sahara,country_Yemen,country_Zambia,country_Zimbabwe
0,42,53936,0.9,13227.120,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,49,82468,0.6,12674.040,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,55,56941,0.3,5354.115,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,24,60651,0.2,2606.510,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,64,81884,0.9,18984.780,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,42,98170,0.7,17435.950,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
996,39,59174,0.9,11662.830,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
997,50,59808,0.4,7196.160,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
998,50,58272,0.7,13939.520,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999,38,32512,0.5,8312.800,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [11]:
dataset.columns

Index(['age', 'income', 'purchase_frequency', 'spending', 'gender_Male',
       'education_High School', 'education_Master', 'education_PhD',
       'country_Albania', 'country_Algeria',
       ...
       'country_Uruguay', 'country_Uzbekistan', 'country_Vanuatu',
       'country_Venezuela', 'country_Vietnam', 'country_Wallis and Futuna',
       'country_Western Sahara', 'country_Yemen', 'country_Zambia',
       'country_Zimbabwe'],
      dtype='object', length=246)

In [12]:
independent=dataset[['age', 'income', 'purchase_frequency', 'gender_Male',
       'education_High School', 'education_Master', 'education_PhD',
       'country_Albania', 'country_Algeria', 'country_Uruguay', 'country_Uzbekistan', 'country_Vanuatu',
       'country_Venezuela', 'country_Vietnam', 'country_Wallis and Futuna',
       'country_Western Sahara', 'country_Yemen', 'country_Zambia',
       'country_Zimbabwe']]
dependent=dataset[['spending']]

In [13]:
independent

,age,income,purchase_frequency,gender_Male,education_High School,education_Master,education_PhD,country_Albania,country_Algeria,country_Uruguay,country_Uzbekistan,country_Vanuatu,country_Venezuela,country_Vietnam,country_Wallis and Futuna,country_Western Sahara,country_Yemen,country_Zambia,country_Zimbabwe
0,42,53936,0.9,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,49,82468,0.6,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
2,55,56941,0.3,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,24,60651,0.2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,64,81884,0.9,True,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,42,98170,0.7,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
996,39,59174,0.9,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
997,50,59808,0.4,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
998,50,58272,0.7,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
999,38,32512,0.5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [14]:
dependent

      spending
0    13227.120
1    12674.040
2     5354.115
3     2606.510
4    18984.780
..         ...
995  17435.950
996  11662.830
997   7196.160
998  13939.520
999   8312.800

[1000 rows x 1 columns]

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.2,random_state=11)

In [16]:
x_train

,age,income,purchase_frequency,gender_Male,education_High School,education_Master,education_PhD,country_Albania,country_Algeria,country_Uruguay,country_Uzbekistan,country_Vanuatu,country_Venezuela,country_Vietnam,country_Wallis and Futuna,country_Western Sahara,country_Yemen,country_Zambia,country_Zimbabwe
832,36,30182,0.8,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
797,55,95225,0.7,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
49,61,20444,0.4,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
867,32,33833,0.1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
514,55,51216,1.0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,27,28977,0.8,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
91,37,28601,0.8,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
80,61,85358,0.4,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
703,51,81139,1.0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
921,41,66114,0.3,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False

In [17]:
y_train

      spending
832  11607.280
797  13132.875
49    8008.880
867   1269.165
514  24560.800
..         ...
337   9159.080
91   14744.040
80   10507.160
703  19056.950
921   6091.710

[800 rows x 1 columns]

In [18]:
x_test

,age,income,purchase_frequency,gender_Male,education_High School,education_Master,education_PhD,country_Albania,country_Algeria,country_Uruguay,country_Uzbekistan,country_Vanuatu,country_Venezuela,country_Vietnam,country_Wallis and Futuna,country_Western Sahara,country_Yemen,country_Zambia,country_Zimbabwe
25,56,36311,0.4,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
464,28,71517,0.8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
372,50,82208,0.2,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
730,45,27374,0.3,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
757,21,32382,1.0,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,22,36169,0.1,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
449,50,52635,0.8,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
221,47,41270,0.7,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
741,51,38324,0.1,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
572,48,32913,0.2,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False

In [19]:
y_test

      spending
25    5526.220
464  13260.680
372   2822.080
730   6410.610
757   6619.100
..         ...
278    880.845
449  16505.400
221  11944.450
741   2191.620
572   3329.130

[200 rows x 1 columns]

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
regressor=LinearRegression() 
regressor.fit(x_train,y_train)

LinearRegression()

In [22]:
y_pred=regressor.predict(x_test)
y_pred

array([[ 4863.47317436],
       [13089.36329284],
       [ 2137.87152243],
       [ 7274.04498587],
       [12158.47760078],
       [ 8960.05736837],
       [ 4052.75150468],
       [13592.37670706],
       [13823.28875369],
       [17402.03462492],
       [10118.04646186],
       [ 6323.56061922],
       [ 4276.42059983],
       [ 3571.39958418],
       [ 2945.56416192],
       [ 9434.74347335],
       [ 8973.0983792 ],
       [12570.10308271],
       [ 6592.29729831],
       [ 6385.10109611],
       [17315.95986491],
       [14578.75841145],
       [ 9086.87767685],
       [10685.86954307],
       [12760.76112119],
       [ 7997.36294161],
       [ 1736.36307284],
       [14229.12185352],
       [10532.88214719],
       [ 5657.40976607],
       [11084.11322381],
       [ 8348.99495625],
       [15886.82901501],
       [10895.11494088],
       [ 9264.76303729],
       [16583.69775445],
       [17618.70571907],
       [20302.83302029],
       [16272.29308947],
       [12810.53228345],
       [ 4605.12589392],
       [18485.71149833],
       [ 2491.84086528],
       [10785.48164261],
       [ 3986.48775621],
       [14661.80119359],
       [ 4170.94798681],
       [ 4045.07105579],
       [ 7860.18916607],
       [ 5812.58737243],
       [12230.7710638 ],
       [ 9914.10283358],
       [17364.28360172],
       [ 5079.14331672],
       [ 4458.91526672],
       [ 2529.98620779],
       [ 5084.38373119],
       [ 5557.20127702],
       [14579.16854304],
       [ 4466.78187055],
       [ 5576.72309038],
       [11393.1888999 ],
       [ 5018.04258642],
       [ 7031.86500696],
       [15833.79805541],
       [-1623.73069582],
       [ 1540.00329686],
       [ 3602.83575553],
       [ 4526.97606245],
       [ 4592.94679277],
       [14639.27928389],
       [ 6461.93331173],
       [11677.94072157],
       [17742.64719226],
       [14457.76421907],
       [ 4943.04339251],
       [ 5127.12593377],
       [16006.37604239],
       [ 9723.65236534],
       [ 5986.81248119],
       [ 6580.71792777],
       [15879.54828983],
       [13479.83458577],
       [ 4767.77070331],
       [ 1946.23356685],
       [ 5231.95812289],
       [ 5619.25636511],
       [ 8218.00962109],
       [-3060.31148334],
       [ 6549.50427449],
       [ 6487.84795976],
       [11222.37770082],
       [ 6827.5885426 ],
       [   77.13415222],
       [13524.78480467],
       [ 4461.03962762],
       [ 4384.33310374],
       [10444.30620448],
       [11497.16214323],
       [15499.4248523 ],
       [ 6335.35933732],
       [14022.60207263],
       [ 1727.02871959],
       [-1881.83237347],
       [ 8306.38590049],
       [ 5530.24012682],
       [ 7191.92922826],
       [ 8094.42946417],
       [19216.89241376],
       [12232.53623279],
       [ 9106.06966678],
       [ 5346.96312836],
       [13486.09701752],
       [10646.35065717],
       [ 9682.44659106],
       [10247.47669201],
       [18820.97974778],
       [20582.08984855],
       [ 8413.64184602],
       [15870.2574807 ],
       [ -618.57850097],
       [ 6934.15554173],
       [ 3824.41876576],
       [12169.90055061],
       [ 5193.31514078],
       [ 7766.03521054],
       [15810.70055451],
       [12219.42476144],
       [ 1664.55391977],
       [ 8330.37621887],
       [ 9224.68697458],
       [ 5561.25054412],
       [11824.99452265],
       [14755.41380042],
       [15746.78077175],
       [-3489.45640832],
       [ 1688.27037669],
       [15760.43508387],
       [11989.22494414],
       [ 6507.83353688],
       [18328.05724123],
       [ 2161.10324349],
       [ 5280.91559658],
       [16625.95763599],
       [12968.09524146],
       [14087.71687527],
       [14339.94940795],
       [ 7453.42076562],
       [ -273.70326398],
       [15090.62082677],
       [ 2283.20823077],
       [ 5223.86265   ],
       [ 7108.8760043 ],
       [ 7665.77050698],
       [14587.37283323],
       [ 8507.11140516],
       [ 9222.08379704],
       [16486.82551643],
       [ 5085.337589  ],
       [ -136.64415364],
       [14567.53130822],
       [13692.6640186 ],
       [15578.95630502],
       [  529.76240791],
       [13854.25548705],
       [ 9857.297878  ],
       [19288.28738533],
       [11745.29712164],
       [12698.17905567],
       [ 6595.57666537],
       [14656.39137335],
       [ 9995.17565116],
       [ 7967.39632841],
       [14557.37111877],
       [16124.10237095],
       [ 2114.58336274],
       [ 3398.64256612],
       [13498.6091643 ],
       [ 7293.31472586],
       [12029.30360271],
       [19605.88653079],
       [ 9026.10481727],
       [15807.15588404],
       [ 9079.67221157],
       [ 7963.41977775],
       [11340.76162402],
       [11095.92679134],
       [ 4756.00180388],
       [11301.68711862],
       [ 3228.52972779],
       [13180.68332642],
       [ 6721.46180791],
       [13351.01086333],
       [17737.15405391],
       [13098.74398211],
       [-2182.88326013],
       [15986.26527013],
       [12107.87725981],
       [ 3520.26206391],
       [ 3279.64173622]])

In [23]:
from sklearn.metrics import r2_score
r2score=r2_score(y_test,y_pred)

In [24]:
r2score

0.9322069436795565